version: '3'
services:
  vue-site:
    build:
      context: ./
      dockerfile: vue.dockerfile
    container_name: vue-site
    ports:
      - 9080:8080
      - 9001:8000
    environment:
      TZ: "Asia/Tokyo"
    command: "tail -f /dev/null"
    networks:
      seventh-project-net:
    volumes:
      - ./vue.js:/app
  vue-service:
    build:
      context: ./
      dockerfile: vue.dockerfile
    container_name: vue-service
    ports:
      - 10080:8080
      - 10001:8000
    environment:
      TZ: "Asia/Tokyo"
    command: "tail -f /dev/null"
    networks:
      seventh-project-net:
    volumes:
      - ./vue.js:/app
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
    environment:
      TZ: "Asia/Tokyo"
    networks:
      seventh-project-net:
    volumes:
      - ./nginx:/var/www
      - ./static:/static
  flask:
    build:
      context: ./
      dockerfile: flask.dockerfile
    container_name: flask
    ports:
      - 6000
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MYSQL_URL=${MYSQL_URL}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    # command: 
    #   - "/bin/bash"
    #   - "-c"
    #   - >
    #     chmod 755 /app/uwsgi.ini;
    #     uwsgi --ini /app/uwsgi.ini;
    command: /bin/bash -c "tail -f /dev/null"
    networks:
      seventh-project-net:
    volumes:
      - ./flask:/app/site
  django:
    build:
      context: ./
      dockerfile: django.dockerfile
    container_name: django
    ports:
      - 6000
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    # command: 
    #   - "/bin/bash"
    #   - "-c"
    #   - >
    #     chmod 755 /app/uwsgi.ini;
    #     uwsgi --ini /app/uwsgi.ini;
    command: /bin/bash -c "tail -f /dev/null"
    networks:
      seventh-project-net:
    volumes:
      - ./django:/app/project
  postgres:
    image: postgres:11.2
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      seventh-project-net:
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  mysql:
    image: mysql:8.0.17
    container_name: mysql
    ports:
      - 3307:3306
    networks:
      seventh-project-net:
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
networks:
  seventh-project-net:
      driver: bridge
      ipam:
          driver: default
          config:
            - subnet: 172.10.0.0/24
